networks:
  dem:
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    networks:
      - dem
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORTS: 80
    ports:
      - "5005:80"
    depends_on:
      - postgres
    networks:
      - dem

  load_service:
    build: .
    image: sql-loader-load-service:latest
    env_file:
      - .env
    volumes:
      - ./file_test.json:/app/file_test.json
    networks:
      - dem
    depends_on:
      postgres:
        condition: service_healthy